version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:tap-tester-v4
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -mvenv /usr/local/share/virtualenvs/tap-surveymonkey
            source /usr/local/share/virtualenvs/tap-surveymonkey/bin/activate
            pip install -U 'pip==22.2.2' 'setuptools==65.3.0'
            pip install .[dev]
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-surveymonkey/bin/activate
            pylint tap_surveymonkey -d C,R,W
      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-surveymonkey/bin/activate
            pip install coverage
            pip install nose coverage parameterized
            nosetests --with-coverage --cover-erase --cover-package=tap_surveymonkey --cover-html-dir=htmlcov tests/unittests
            coverage html

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
