version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -mvenv /usr/local/share/virtualenvs/tap-surveymonkey
            source /usr/local/share/virtualenvs/tap-surveymonkey/bin/activate
            pip install -U pip 'setuptools==65.3.0'
            pip install .[dev]
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-surveymonkey/bin/activate
            pylint tap_surveymonkey -d C,R,W
      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-surveymonkey/bin/activate
            pip install nose2 parameterized nose2[coverage_plugin]>=0.6.5
            nose2 --with-coverage -v -s tests/unittests

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
